name: chickelit.online deployment

on: 
  push: 
    branches: [main]
  pull_request: 
    branches: [main]
  
  workflow_dispatch:

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - name: Build 
        run: echo Building the app
  deploy-development:
    runs-on: ubuntu-latest
    environment: 
      name: development
      url: ${{vars.URL}}
    steps: 
      - name: Repo Checkout
        uses: actions/checkout@v1
      - name: Hostinger Deployment
        uses: easingthemes/ssh-deploy@main
        with: 
          SSH_PRIVATE_KEY: ${{secrets.SERVER_SSH_KEY}}
          ARGS: "-rlgoDzvc --delete"
          SOURCE: "./"
          REMOTE_HOST: ${{vars.REMOTE_HOST}}
          REMOTE_USER: ${{vars.REMOTE_USER}}
          REMOTE_PORT: ${{vars.REMOTE_PORT}}
          TARGET: ${{vars.TARGET}}
      - name: VPS Build
        uses: appleboy/ssh-action@v1.0.3
        with: 
          key: ${{secrets.SERVER_SSH_KEY}}
          host: ${{vars.REMOTE_HOST}}
          username: ${{vars.REMOTE_USER}}
          port: ${{vars.REMOTE_PORT}}
          script: |
            echo "Starting VPS Build"
            echo "TARGET: ${{vars.TARGET}}"
            # cd /var/www/chickelit.online
            # git pull origin main
            # npm install --only=prod
            # npm run build --if-present
          debug: true
        env:
          TARGET: /var/www/chickelit.online
