name: chickelit.online testing

permissions: 
  contents: write

on:
  push:
    branches: [review]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Using Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: 18.17.1
      - name: Run test suites
        run: |
          npm install
          npm run test
          git checkout -b master
          git pull origin master
          git push -u origin master

