name: chickelit.online testing

on:
  push:
    branches: [review]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Using Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: 18.17.1
      - name: Run test suites
        run: |
          npm install
          npm run test
      - name: Add github SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with: 
          ssh-private-key: ${{ secrets.GH_SSH_KEY }}
      - name: Push to master
        run: |
          git init
          git remote add origin git@github.com:${{ vars.GH_USER }}/${{ vars.GH_REPO }}.git
          git push -u origin master

          