name: chickelit.online testing

on:
  push:
    branches: [review]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Using Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: 18.17.1
      - name: Run test suites
        run: |
          npm install
          npm run test
      - name: Push to master
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/${{ vars.GITHUB_USER }}/${{ vars.GITHUB_REPO }}.git
          git push -u origin master
